services:
  web: 
    image: nginx:alpine
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 60M
        reservations:
          cpus: '0.20'
          memory: 30M
    build: .
    container_name: NoBalancer
    environment:
      - SERVER_NAME=NoBalancer
      - SERVER_IP=127.0.0.1
    ports:
      - "8000:80"
      
  

